models:
  deforestration_detection:
    network: fpn50
    channels:
      - rgb
    weights: /code/clearcuts/fpn50_new_markup_320_rnd_crop.pth

prediction:
  save_path: /code/data
  threshold: 0.3
  input_size: 224