version: "2"
services:
  db:
    build:
      context: ./
      dockerfile: postgis.Dockerfile
    expose:
      - 5432
    env_file:
      - db.env
    volumes:
      - ./:/code

  model:
    build:
      context: ./model
      dockerfile: model.Dockerfile
    volumes:
      - ./model/:/model
      - ./data/:/data
    working_dir: /model
    ports:
      - "5000:5000"
    command: /bin/bash -c "python app.py"

  react:
    image: node:10.15.0
    volumes:
      - ./frontend:/frontend
    working_dir: /frontend
    ports:
      - "3000:3000"
    depends_on:
      - django
    command: /bin/bash -c "npm install && npm run-script start"

  django:
    build:
      context: ./
      dockerfile: django.Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=clearcut_detection_backend.settings
    volumes:
      - ./:/code
    working_dir: /code
    depends_on:
      - db
    expose:
      - 9000
    command: /bin/bash -c "pip install -r requirements.txt && exec invoke runbackend"

  nginx:
    image: nginx:1.15.8
    depends_on:
      - django
    extra_hosts:
      - "react:127.0.0.1"
    expose:
      - "9000"
    environment:
      - VIRTUAL_HOST=clearcut.quantumobile.com
      - VIRTUAL_PORT=9000
      - LETSENCRYPT_HOST=clearcut.quantumobile.com
      - LETSENCRYPT_EMAIL=i.lukinov@quantumobile.com
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
