# Dev docker's file

version: "2"
services:
  db:
    build:
      context: ./
      dockerfile: postgis.Dockerfile
    expose:
      - 5432
    env_file:
      - db.env
    volumes:
      - ./:/code
  react:
    image: node:10.15.0
    volumes:
      - ./frontend:/frontend
    working_dir: /frontend
    ports:
      - "3000:3000"
    command: /bin/bash -c "npm install && npm run-script start"
  django:
    build:
      context: ./
      dockerfile: django.Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=clearcut_detection_backend.settings

    volumes:
      - ./:/code
    working_dir: /code
    links:
      - db:db
    expose:
      - 9000
    command: /bin/bash -c "pip install -r requirements.txt && exec invoke runbackend"

  nginx:
    image: nginx:1.15.8
    links:
      - django:django
    extra_hosts:
      - "react:127.0.0.1"
    expose:
      - "9000"
    environment:
      - VIRTUAL_HOST=clearcut.quantumobile.com
      - VIRTUAL_PORT=9000
      - LETSENCRYPT_HOST=clearcut.quantumobile.com
      - LETSENCRYPT_EMAIL=i.lukinov@quantumobile.com
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/web.conf
