# Dev docker's file

version: "2"
services:
  db:
    build:
      context: ./
      dockerfile: postgis.Dockerfile
    expose:
      - 5432
    env_file:
      - db.env
    volumes:
      - ./:/code
  react:
    image: node:10.15.0
    volumes:
      - ./frontend:/frontend
    working_dir: /frontend
    ports:
      - "3000:3000"
    command: /bin/bash -c "npm install && npm run-script start"
  django:
    build:
      context: ./
      dockerfile: django.Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=clearcut_detection_backend.settings

    volumes:
      - ./:/code
    working_dir: /code
    links:
      - db:db
    expose:
      - 9000
    ports:
      - "9000:9000"
    command: /bin/bash -c "pip install -r requirements.txt && exec invoke rundev"
