db_stage:
  build: ./
  dockerfile: postgis.Dockerfile
  expose:
    - 5432
  env_file:
    - db.env
  volumes:
    - db-data:/var/lib/postgresql/data
    - ./:/code

model_stage:
  build: ./model
  dockerfile: model.Dockerfile
  env_file:
    - ./model/model.env
  volumes:
    - ./model/:/model
    - ./data/:/model/data
  working_dir: /model
  ports:
    - "5001:5000"
  command: /bin/bash -c "pip install -r requirements.txt && python app.py"

react_stage:
  image: node:10.15.0
  volumes:
    - ./frontend:/frontend
  working_dir: /frontend
  ports:
    - "3000:3000"
  links: 
    - "django_stage"
  command: /bin/bash -c "npm install && npm run-script build"

django_stage:
  build: ./
  dockerfile: django.Dockerfile
  environment:
    - DJANGO_SETTINGS_MODULE=clearcut_detection_backend.prod_settings
  env_file:
   - db.env 
   - django.env
  volumes:
    - ./:/code
  working_dir: /code
  links:
    - "db_stage"
    - "model_stage"
  expose:
    - 9000
  command: /bin/bash -c "pip install -r requirements.txt && exec invoke runbackend"

nginx_stage:
  image: nginx:1.15.8
  links:
    - "django_stage"
  expose:
    - "8082"
  environment:
    - VIRTUAL_HOST=clearcut1.quantumobile.com
    - VIRTUAL_PORT=8082
    - LETSENCRYPT_HOST=clearcut1.quantumobile.com
    - LETSENCRYPT_EMAIL=o.tsiapa@quantumobile.com
  volumes:
    - ./nginx/nginx_stage.conf:/etc/nginx/conf.d/default.conf
    - ./frontend/build:/frontend/build

