db_stage:
  build: ./
  dockerfile: postgis.Dockerfile
  expose:
    - 5432
  ports:
    - "5433:5432"
  env_file:
    - db.env
  volumes:
    - ./db-data_stage/data:/var/lib/postgresql/data
    - ./:/code

#model_stage:
#  build: ./model
#  dockerfile: model.Dockerfile
#  env_file:
#    - ./model/model.env
#  environment:
#    - MODEL_HOST=model_stage
#    - MODEL_PORT=5000
#    - MODEL_ENDPOINT=raster_prediction
#  volumes:
#    - ./model/:/model
#    - ./data/:/model/data
#  working_dir: /model
#  ports:
#    - "5001:5000"
#  command: /bin/bash -c "pip install -r requirements.txt && python app.py"

model_stage_2:
  build: ./model2
  dockerfile: model.Dockerfile
  env_file:
    - ./model2/model.env
  volumes:
    - ./model2/:/model
    - ./data/:/model/data
  working_dir: /model
  expose:
      - 5000
  command: /bin/bash -c "pip install -r requirements.txt && ./run_predict.sh"  # todo

react_stage:
  image: node:10.15.0
  volumes:
    - ./frontend:/frontend
  working_dir: /frontend
  ports:
    - "3001:3000"
  links: 
    - "django_stage"
  command: /bin/bash -c "npm install && npm run-script build"

django_stage:
  build: ./
  dockerfile: django.Dockerfile
  environment:
    - DJANGO_SETTINGS_MODULE=clearcut_detection_backend.prod_settings
    - DB_HOST=db_stage
    - DOWNLOAD_IMG=False
  env_file:
   - db.env 
   - django.env
  volumes:
    - ./:/code
  working_dir: /code
  links:
    - "db_stage"
#    - "model_stage"
    - "model_stage_2"
  expose:
    - 9000
  command: /bin/bash -c "pip install -r requirements.txt && exec invoke runbackend --createdb"

nginx_stage:
  image: nginx:1.15.8
  links:
    - "django_stage"
  expose:
    - "8082"
  environment:
    - VIRTUAL_HOST=clearcut1.quantumobile.com
    - VIRTUAL_PORT=8082
    - LETSENCRYPT_HOST=clearcut1.quantumobile.com
    - LETSENCRYPT_EMAIL=o.tsiapa@quantumobile.com
  volumes:
    - ./nginx/nginx_stage.conf:/etc/nginx/conf.d/default.conf
    - ./frontend/build:/frontend/build
    - ./db-data_stage/data:/var/lib/postgresql/data

