version: '3'
services:
  db:
    build:
      context: ./
      dockerfile: postgis.Dockerfile
    image: clearcut_detection/database
    ports:
    - 5432:5432
    expose:
      - 5432
    env_file:
      - db.env
    volumes:
      - ./:/code
#      - ./postgres_data:/var/lib/postgresql/data/

  react:
    image: node:10.15.0
    volumes:
      - ./frontend:/frontend
    working_dir: /frontend
    expose:
      - 3000
    depends_on:
      - django
    command: /bin/bash -c "npm install && npm run-script start"

  model:
    build:
      context: ./model
      dockerfile: model.Dockerfile
    image: clearcut_detection/model
    env_file:
      - ./model/model.env
    volumes:
      - ./model/:/model
      - ./data/:/model/data
    working_dir: /model
    ports:
      - '5000:5000'
    command: /bin/bash -c "pip install -r requirements.txt && python app.py"

  django:
    build:
      context: ./
      dockerfile: django.Dockerfile
    image: clearcut_detection/backend
    environment:
      - DJANGO_SETTINGS_MODULE=clearcut_detection_backend.settings
    env_file:
      - django.env
    volumes:
      - ./:/code
#    working_dir: /code
    depends_on:
      - db

    ports:
      - 9000:9000
    expose:
      - 9000
    command: python /code/manage.py runserver 0.0.0.0:9000

  nginx:
    image: nginx:1.15.8
    depends_on:
      - django
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/dev.nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
    data:
#    postgres_data:
